version: "3.8"

services:
  rentalservice:
    image: kevmdf/rentalservice
    container_name: rentalservice
    ports:
      - "8080:8080"
    depends_on:
      - microservicephp
    environment:
      - SPRING_PROFILES_ACTIVE=default
      - customer.service.url=http://microservicephp
    networks:
      - mynetwork

  microservicephp:
    image: kevmdf/microservice-php-kevin
    container_name: microservicephp
    ports:
      - "80:80"
    networks:
      - mynetwork

networks:
  mynetwork:
